#!/usr/bin/env python3
"""Build a separate, fail-fast Vulkan interop shim set.

This is intentionally independent of build-headless-shims.py and never edits
rootfs/gpu-compat-20260921/shims or the private runtime.  It derives the
symbols needed by the recovered Samsung Vulkan HAL and emits only graphics
interop sentinels: AHardwareBuffer, SGR metadata, and sync_wait.  The
SBWCHelper/HIDL/ION/DRM closure remains real and is not stubbed here.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_VENDOR = ROOT / "rootfs/gpu-vendor-reuse-20260921/lib64/hw/vulkan.samsung.so"
DEFAULT_OUT = ROOT / "rootfs/gpu-compat-20260921/shims-vulkan"
DEFAULT_CLANG = (
    ROOT
    / "rootfs/gpu-compat-20260921/toolchain/android-ndk-r27c"
    / "toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android31-clang"
)
SYMBOL_RE = re.compile(r"^\s*\d+:\s+\S+\s+\S+\s+\S+\s+\S+\s+\S+\s+(\S+)(?:\s+(.*))?$")
AHB = {
    "AHardwareBuffer_acquire",
    "AHardwareBuffer_allocate",
    "AHardwareBuffer_describe",
    "AHardwareBuffer_getId",
    "AHardwareBuffer_getNativeHandle",
    "AHardwareBuffer_release",
}


def command(args: list[str], *, capture: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(args, check=True, text=True, capture_output=capture)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def manifest_path(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def undefined_symbols(path: Path) -> set[str]:
    result: set[str] = set()
    text = command(["readelf", "--dyn-syms", "--wide", str(path)]).stdout
    for line in text.splitlines():
        match = SYMBOL_RE.match(line)
        if not match or match.group(1) != "UND":
            continue
        names = (match.group(2) or "").split()
        if names:
            result.add(names[0].split("@", 1)[0])
    return result


def dynamic_exports(path: Path) -> set[str]:
    result: set[str] = set()
    text = command(["readelf", "--dyn-syms", "--wide", str(path)]).stdout
    for line in text.splitlines():
        parts = line.split()
        if not parts or not parts[0].endswith(":") or "UND" in parts:
            continue
        try:
            default = parts.index("DEFAULT")
            name = parts[default + 2]
        except (ValueError, IndexError):
            continue
        result.add(name.split("@", 1)[0])
    return result


def soname(path: Path) -> str:
    text = command(["readelf", "-d", str(path)]).stdout
    for line in text.splitlines():
        if "(SONAME)" in line:
            match = re.search(r"\[(.*?)\]", line)
            if match:
                return match.group(1)
    raise SystemExit(f"missing SONAME: {path}")


def needed(path: Path) -> list[str]:
    result = []
    for line in command(["readelf", "-dW", str(path)]).stdout.splitlines():
        if "(NEEDED)" not in line:
            continue
        match = re.search(r"\[(.*?)\]", line)
        if match:
            result.append(match.group(1))
    return result


def make_source(symbols: list[str], role: str) -> str:
    lines = [
        "/* Generated by tools/gpu-compat/build-vulkan-shims.py. */",
        "/* Every entry fails closed; this is not a graphics implementation. */",
        "#define _GNU_SOURCE",
        "#include <stdio.h>",
        "#include <unistd.h>",
        "",
        "__attribute__((noreturn))",
        "static void vulkan_shim_abort(const char *symbol)",
        "{",
        '    (void)dprintf(STDERR_FILENO, "VULKAN_SHIM_ABORT role=%s symbol=%s\\n",',
        f'                   "{role}", symbol);',
        "    _exit(125);",
        "    __builtin_unreachable();",
        "}",
        "",
    ]
    for symbol in symbols:
        lines.extend(
            [
                '__attribute__((visibility("default"), noreturn))',
                f"void {symbol}(void)",
                "{",
                f'    vulkan_shim_abort("{symbol}");',
                "}",
                "",
            ]
        )
    return "\n".join(lines)


def nativewindow_map(symbols: list[str]) -> str:
    return "\n".join(
        [
            "LIBNATIVEWINDOW {",
            "  global:",
            *[f"    {symbol};" for symbol in symbols],
            "  local:",
            "    *;",
            "};",
            "",
        ]
    )


def build_one(
    compiler: Path,
    source: Path,
    output: Path,
    soname_value: str,
    version_script: Path | None = None,
    *,
    android: bool = True,
    no_stdlib: bool = False,
) -> None:
    args = [str(compiler), "-std=c11", "-Wall", "-Wextra", "-Werror", "-fPIC",
            "-fvisibility=hidden", "-shared", "-Wl,--no-undefined",
            f"-Wl,-soname,{soname_value}"]
    if no_stdlib:
        args.insert(1, "-nostdlib")
    if version_script is not None:
        args.append(f"-Wl,--version-script={version_script}")
    args.extend(["-o", str(output), str(source)])
    if not android:
        args.insert(1, "-Wl,--no-as-needed")
    command(args)


def validate(path: Path, exports: set[str], expected_soname: str) -> None:
    actual = dynamic_exports(path)
    if actual != exports:
        raise SystemExit(
            f"export mismatch {path}: expected={sorted(exports)} actual={sorted(actual)}"
        )
    actual_soname = soname(path)
    if actual_soname != expected_soname:
        raise SystemExit(
            f"SONAME mismatch {path}: expected={expected_soname} actual={actual_soname}"
        )


def host_abort_test(host_paths: dict[str, Path], symbols: dict[str, list[str]]) -> None:
    probes = [
        ("nativewindow", symbols["nativewindow"][0]),
        ("mapper", symbols["mapper"][0]),
        ("sync", "sync_wait"),
    ]
    for role, symbol in probes:
        script = (
            "import ctypes,sys\n"
            "lib=ctypes.CDLL(sys.argv[1])\n"
            "getattr(lib,sys.argv[2])()\n"
        )
        result = subprocess.run(
            [sys.executable, "-c", script, str(host_paths[role]), symbol],
            text=True,
            capture_output=True,
        )
        if result.returncode != 125 or f"symbol={symbol}" not in result.stderr:
            raise SystemExit(
                f"host abort test failed role={role} symbol={symbol} "
                f"returncode={result.returncode} stderr={result.stderr!r}"
            )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--vendor", type=Path, default=DEFAULT_VENDOR)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--clang", type=Path, default=DEFAULT_CLANG)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    vendor = args.vendor.resolve()
    output = args.out.resolve()
    clang = args.clang.resolve()
    if not vendor.is_file():
        raise SystemExit(f"Vulkan vendor object not found: {vendor}")
    if not clang.is_file() or not clang.stat().st_mode & 0o111:
        raise SystemExit(f"Android clang not executable: {clang}")

    imports = undefined_symbols(vendor)
    ahb = sorted(s for s in imports if s.startswith("AHardwareBuffer_"))
    mapper = sorted(s for s in imports if s.startswith("_Z") and "sgr_intf" in s)
    sbwc = sorted(s for s in imports if s.startswith("_ZN10SBWCHelper"))
    unexpected_ahb = set(ahb) - AHB
    if set(ahb) != AHB or unexpected_ahb:
        raise SystemExit(f"unexpected Vulkan AHardwareBuffer imports: {ahb}")
    if len(mapper) != 27:
        raise SystemExit(f"unexpected Vulkan SGR metadata import count: {len(mapper)}")
    if sbwc != sorted(s for s in imports if s.startswith("_ZN10SBWCHelper")):
        raise SystemExit("unreachable SBWCHelper import audit")
    if "sync_wait" not in imports:
        raise SystemExit("Vulkan HAL no longer imports sync_wait; refusing stale shim set")

    output.mkdir(parents=True, exist_ok=True)
    sources = {
        "nativewindow": output / "nativewindow-shim.c",
        "mapper": output / "mapper-shim.c",
        "sync": output / "sync-shim.c",
        "hardware": output / "hardware-carrier.c",
        "gralloctypes": output / "gralloctypes-carrier.c",
    }
    sources["nativewindow"].write_text(make_source(ahb, "nativewindow"), encoding="utf-8")
    sources["mapper"].write_text(make_source(mapper, "mapper"), encoding="utf-8")
    sources["sync"].write_text(make_source(["sync_wait"], "sync"), encoding="utf-8")
    # Vulkan has a DT_NEEDED libhardware.so but no LIBHARDWARE-versioned
    # undefined symbols. This empty carrier satisfies only that file-level
    # dependency; it is not a hardware implementation and is not suitable for
    # a mode that calls hardware-module APIs.
    sources["hardware"].write_text(
        "/* Empty SONAME carrier: Vulkan has no imported LIBHARDWARE symbols. */\n",
        encoding="utf-8",
    )
    sources["gralloctypes"].write_text(
        "/* Empty SONAME carrier: the real Exynos buffer core has no imported gralloc symbols. */\n",
        encoding="utf-8",
    )
    map_path = output / "nativewindow.map"
    map_path.write_text(nativewindow_map(ahb), encoding="utf-8")

    artifacts = {
        "nativewindow": output / "libnativewindow.so",
        "mapper": output / "android.hardware.graphics.mapper@4.0-impl-sgr.so",
        "sync": output / "libsync.so",
        "hardware": output / "libhardware.so",
        "gralloctypes": output / "libgralloctypes.so",
    }
    build_one(clang, sources["nativewindow"], artifacts["nativewindow"],
              "libnativewindow.so", map_path)
    build_one(clang, sources["mapper"], artifacts["mapper"],
              "android.hardware.graphics.mapper@4.0-impl-sgr.so")
    build_one(clang, sources["sync"], artifacts["sync"], "libsync.so")
    build_one(clang, sources["hardware"], artifacts["hardware"], "libhardware.so", no_stdlib=True)
    build_one(clang, sources["gralloctypes"], artifacts["gralloctypes"], "libgralloctypes.so", no_stdlib=True)
    validate(artifacts["nativewindow"], set(ahb), "libnativewindow.so")
    validate(artifacts["mapper"], set(mapper), "android.hardware.graphics.mapper@4.0-impl-sgr.so")
    validate(artifacts["sync"], {"sync_wait"}, "libsync.so")
    validate(artifacts["hardware"], set(), "libhardware.so")
    validate(artifacts["gralloctypes"], set(), "libgralloctypes.so")
    if needed(artifacts["hardware"]):
        raise SystemExit("libhardware carrier unexpectedly gained dependencies")
    if needed(artifacts["gralloctypes"]):
        raise SystemExit("libgralloctypes carrier unexpectedly gained dependencies")

    with tempfile.TemporaryDirectory(prefix="vulkan-shims-host-") as temporary:
        host = Path(temporary)
        host_paths = {}
        for role in ["nativewindow", "mapper", "sync"]:
            host_paths[role] = host / artifacts[role].name
            build_one(Path(shutil.which("cc") or "cc"), sources[role], host_paths[role],
                      host_paths[role].name,
                      map_path if role == "nativewindow" else None, android=False)
        host_abort_test(host_paths, {"nativewindow": ahb, "mapper": mapper, "sync": ["sync_wait"]})

    manifest = {
        "generator": "tools/gpu-compat/build-vulkan-shims.py",
        "scope": "separate Vulkan loader-closure sentinels; no runtime replacement",
        "vendor": manifest_path(vendor),
        "vendor_sha256": sha256(vendor),
        "vulkan_imports": {
            "ahardwarebuffer": ahb,
            "sgr_metadata": mapper,
            "sbwchelper_real_imports": sbwc,
            "sync": ["sync_wait"],
        },
        "artifacts": {
            role: {
                "path": manifest_path(path),
                "sha256": sha256(path),
                "soname": soname(path),
                "needed": needed(path),
                "exports": sorted(dynamic_exports(path)),
            }
            for role, path in artifacts.items()
        },
        "host_abort_test": "passed",
        "real_closure_not_stubbed": [
            "libsbwchelper.so",
            "libexynosgraphicbuffer_core.so",
            "libion_exynos.so",
            "libdrm_sgpu.so",
            "libdrm.so",
            "libeis_utils.so",
            "system/lib64/libhidlbase.so",
            "system/lib64/libutils.so",
            "system/lib64/libbase.so",
            "system/lib64/libcutils.so",
            "system/lib64/liblog.so",
            "system/lib64/libc++.so",
        ],
    }
    (output / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(manifest, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
