#!/usr/bin/env python3
"""Build fail-fast Android interop shims for the Samsung OpenCL object.

The shims are deliberately not compatibility implementations. Every exported
interop symbol emits its exact name and exits 125 if called. This makes a
headless experiment fail closed when the vendor library unexpectedly crosses
into graphics allocation or sync code.
"""

from __future__ import annotations

import argparse
import ctypes
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_VENDOR = ROOT / "rootfs/gpu-vendor-reuse-20260921/lib64/libSGPUOpenCL.so"
DEFAULT_OUT = ROOT / "rootfs/gpu-compat-20260921/shims"
DEFAULT_CLANG = (
    ROOT
    / "rootfs/gpu-compat-20260921/toolchain/android-ndk-r27c"
    / "toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android31-clang"
)
SYMBOL_RE = re.compile(r"^\s*\d+:\s+\S+\s+\S+\s+\S+\s+\S+\s+\S+\s+(\S+)\s+(\S+)")


def command(args: list[str], *, capture: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        args,
        check=True,
        text=True,
        capture_output=capture,
    )


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def manifest_path(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def imported_symbols(vendor: Path) -> list[str]:
    text = command(["readelf", "--dyn-syms", "--wide", str(vendor)]).stdout
    result: set[str] = set()
    for line in text.splitlines():
        match = SYMBOL_RE.match(line)
        if not match or match.group(1) != "UND":
            continue
        symbol = match.group(2).split("@", 1)[0]
        if symbol.startswith("_Z") or symbol.startswith("AHardwareBuffer_") or symbol == "sync_wait":
            result.add(symbol)
    if not result:
        raise SystemExit("vendor object has no requested interop imports")
    return sorted(result)


def make_source(symbols: list[str], role: str) -> str:
    lines = [
        "/* Deterministically generated by tools/gpu-compat/build-headless-shims.py. */",
        "/* Every entry is a fail-fast diagnostic, never a no-op implementation. */",
        "#define _GNU_SOURCE",
        "#include <stdio.h>",
        "#include <unistd.h>",
        "",
        "__attribute__((noreturn))",
        "static void headless_shim_abort(const char *symbol)",
        "{",
        '    (void)dprintf(STDERR_FILENO, "HEADLESS_SHIM_ABORT role=%s symbol=%s\\n",',
        f'                   "{role}", symbol);',
        "    _exit(125);",
        "    __builtin_unreachable();",
        "}",
        "",
    ]
    for symbol in symbols:
        lines.extend(
            [
                '__attribute__((visibility("default"), noreturn))',
                f"void {symbol}(void)",
                "{",
                f'    headless_shim_abort("{symbol}");',
                "}",
                "",
            ]
        )
    return "\n".join(lines)


def nativewindow_map(symbols: list[str]) -> str:
    exported = [symbol for symbol in symbols if symbol.startswith("AHardwareBuffer_")]
    return "\n".join(
        [
            "LIBNATIVEWINDOW {",
            "  global:",
            *[f"    {symbol};" for symbol in exported],
            "  local:",
            "    *;",
            "};",
            "",
        ]
    )


def dynamic_exports(path: Path) -> set[str]:
    text = command(["readelf", "--dyn-syms", "--wide", str(path)]).stdout
    result: set[str] = set()
    for line in text.splitlines():
        match = SYMBOL_RE.match(line)
        if not match or match.group(1) == "UND":
            continue
        result.add(match.group(2).split("@", 1)[0])
    return result


def soname(path: Path) -> str:
    text = command(["readelf", "-d", str(path)]).stdout
    for line in text.splitlines():
        if "(SONAME)" in line:
            match = re.search(r"\[(.*?)\]", line)
            if match:
                return match.group(1)
    raise SystemExit(f"missing SONAME: {path}")


def build_one(
    clang: Path,
    source: Path,
    output: Path,
    soname_value: str,
    version_script: Path | None = None,
) -> None:
    args = [
        str(clang),
        "-std=c11",
        "-Wall",
        "-Wextra",
        "-Werror",
        "-fPIC",
        "-fvisibility=hidden",
        "-shared",
        "-Wl,--no-undefined",
        f"-Wl,-soname,{soname_value}",
    ]
    if version_script is not None:
        args.append(f"-Wl,--version-script={version_script}")
    args.extend(["-o", str(output), str(source)])
    command(args)


def validate_exports(
    path: Path,
    expected: set[str],
    expected_soname: str,
    *,
    require_version: bool = False,
) -> None:
    actual = dynamic_exports(path)
    if actual != expected:
        raise SystemExit(
            f"export mismatch {path.name}: expected={sorted(expected)} actual={sorted(actual)}"
        )
    actual_soname = soname(path)
    if actual_soname != expected_soname:
        raise SystemExit(
            f"SONAME mismatch {path.name}: expected={expected_soname} actual={actual_soname}"
        )
    if require_version:
        version_info = command(["readelf", "--version-info", str(path)]).stdout
        if "LIBNATIVEWINDOW" not in version_info:
            raise SystemExit(f"missing LIBNATIVEWINDOW version on {path}")


def host_abort_test(host_paths: dict[str, Path], symbols: dict[str, list[str]]) -> None:
    """Load only a generated shim and verify its first call exits 125."""
    probes = [
        ("mapper", symbols["mapper"][0]),
        ("sync", "sync_wait"),
        ("nativewindow", "AHardwareBuffer_acquire"),
    ]
    for role, symbol in probes:
        script = (
            "import ctypes,sys\n"
            "lib=ctypes.CDLL(sys.argv[1])\n"
            "getattr(lib,sys.argv[2])()\n"
        )
        result = subprocess.run(
            [sys.executable, "-c", script, str(host_paths[role]), symbol],
            text=True,
            capture_output=True,
        )
        if result.returncode != 125:
            raise SystemExit(
                f"host shim test failed role={role} symbol={symbol} "
                f"returncode={result.returncode} stderr={result.stderr!r}"
            )
        expected = f"symbol={symbol}"
        if expected not in result.stderr:
            raise SystemExit(
                f"host shim diagnostic missing role={role} symbol={symbol}: "
                f"{result.stderr!r}"
            )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--vendor", type=Path, default=DEFAULT_VENDOR)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--clang", type=Path, default=DEFAULT_CLANG)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    vendor = args.vendor.resolve()
    output = args.out.resolve()
    clang = args.clang.resolve()
    if not vendor.is_file():
        raise SystemExit(f"vendor object not found: {vendor}")
    if not clang.is_file() or not os.access(clang, os.X_OK):
        raise SystemExit(f"Android clang not executable: {clang}")
    if shutil.which("readelf") is None:
        raise SystemExit("readelf is required")

    all_symbols = imported_symbols(vendor)
    mapper_symbols = [symbol for symbol in all_symbols if symbol.startswith("_Z")]
    nativewindow_symbols = [symbol for symbol in all_symbols if symbol.startswith("AHardwareBuffer_")]
    if len(mapper_symbols) != 26 or len(nativewindow_symbols) != 4 or "sync_wait" not in all_symbols:
        raise SystemExit(
            "unexpected interop import set: "
            f"mapper={len(mapper_symbols)} nativewindow={len(nativewindow_symbols)} "
            f"sync_wait={'sync_wait' in all_symbols}"
        )

    output.mkdir(parents=True, exist_ok=True)
    source_paths = {
        "mapper": output / "mapper-shim.c",
        "nativewindow": output / "nativewindow-shim.c",
        "sync": output / "sync-shim.c",
    }
    map_path = output / "nativewindow.map"
    source_paths["mapper"].write_text(make_source(mapper_symbols, "mapper"), encoding="utf-8")
    source_paths["nativewindow"].write_text(
        make_source(nativewindow_symbols, "nativewindow"), encoding="utf-8"
    )
    source_paths["sync"].write_text(make_source(["sync_wait"], "sync"), encoding="utf-8")
    map_path.write_text(nativewindow_map(nativewindow_symbols), encoding="utf-8")

    android_paths = {
        "mapper": output / "android.hardware.graphics.mapper@4.0-impl-sgr.so",
        "nativewindow": output / "libnativewindow.so",
        "sync": output / "libsync.so",
    }
    build_one(
        clang,
        source_paths["mapper"],
        android_paths["mapper"],
        "android.hardware.graphics.mapper@4.0-impl-sgr.so",
    )
    build_one(
        clang,
        source_paths["nativewindow"],
        android_paths["nativewindow"],
        "libnativewindow.so",
        map_path,
    )
    build_one(clang, source_paths["sync"], android_paths["sync"], "libsync.so")
    validate_exports(
        android_paths["mapper"],
        set(mapper_symbols),
        "android.hardware.graphics.mapper@4.0-impl-sgr.so",
    )
    validate_exports(
        android_paths["nativewindow"],
        set(nativewindow_symbols),
        "libnativewindow.so",
        require_version=True,
    )
    validate_exports(android_paths["sync"], {"sync_wait"}, "libsync.so")

    with tempfile.TemporaryDirectory(prefix="headless-shims-host-") as temporary:
        host_dir = Path(temporary)
        host_paths = {
            "mapper": host_dir / android_paths["mapper"].name,
            "nativewindow": host_dir / android_paths["nativewindow"].name,
            "sync": host_dir / android_paths["sync"].name,
        }
        build_one(Path(shutil.which("cc") or "cc"), source_paths["mapper"], host_paths["mapper"], host_paths["mapper"].name)
        build_one(
            Path(shutil.which("cc") or "cc"),
            source_paths["nativewindow"],
            host_paths["nativewindow"],
            host_paths["nativewindow"].name,
            map_path,
        )
        build_one(Path(shutil.which("cc") or "cc"), source_paths["sync"], host_paths["sync"], host_paths["sync"].name)
        host_abort_test(host_paths, {"mapper": mapper_symbols})

    manifest = {
        "generator": "tools/gpu-compat/build-headless-shims.py",
        "vendor": manifest_path(vendor),
        "vendor_sha256": sha256(vendor),
        "imports": {
            "mapper": mapper_symbols,
            "nativewindow": nativewindow_symbols,
            "sync": ["sync_wait"],
        },
        "artifacts": {
            role: {
                "path": manifest_path(path),
                "sha256": sha256(path),
                "soname": soname(path),
                "exports": sorted(dynamic_exports(path)),
            }
            for role, path in android_paths.items()
        },
        "host_abort_test": "passed",
    }
    (output / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(json.dumps(manifest, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
