/* Generated by test-npu-mailbox-msgid-validation.py from pinned kernel C. */
#include <limits.h>
#include <setjmp.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define NPU_MAX_MSG_ID_CNT 64
#define MSGID_POOL_MAGIC 0x18D718D7U
#define PROTO_DRV_REQ_TYPE_FRAME 1
#define PROTO_DRV_REQ_TYPE_NW 2
#define FW_LOGSIZE 0
#define TRUE 1
#define FALSE 0
#define MAILBOX_F2HCTRL_RESPONSE 0
#define MAILBOX_F2HCTRL_NRESPONSE 1
#define COMMAND_DONE 1
#define COMMAND_NDONE 2
#define NPU_ERR_NO_ERROR 0
#define NPU_ERR_NPU_HW_TIMEOUT_RECOVERED 20
#define NPU_ERR_NPU_HW_TIMEOUT_NOTRECOVERABLE 21
#define ERR_TIMEOUT_RECOVERED 100
#define ERR_TIMEOUT 101

typedef uint32_t u32;
typedef int64_t s64;
typedef struct { int counter; } atomic_t;

struct msgid_pool_entry {
	atomic_t occupied;
	int pt_type;
	void *ref;
};

struct msgid_pool {
	struct msgid_pool_entry pool[NPU_MAX_MSG_ID_CNT];
	u32 magic;
};

struct npu_session;
struct npu_nw {
	int result_code;
	int result_value;
	int msgid;
};
struct frame_timestamp { int tv_sec; };
struct frame_output { struct frame_timestamp timestamp[6]; };
struct npu_frame {
	int result_code;
	u32 duration;
	int msgid;
	struct frame_output *output;
};
struct proto_req_nw { struct npu_nw nw; };
struct proto_req_frame { struct npu_frame frame; };

struct message { u32 mid; u32 command; };
enum channel_flag { LOW_CHANNEL, MEDIUM_CHANNEL, HIGH_CHANNEL };
struct command {
	union {
		struct { int request_specific_value; } done;
		struct { int error; } ndone;
	} c;
};
struct mailbox_ctrl { int unused; };
struct mailbox_header { struct mailbox_ctrl f2hctrl[2]; };
struct npu_if_mbox_ops {
	int (*nw_get_result)(int *, struct npu_nw *);
	int (*frame_get_result)(int *, struct npu_frame *, enum channel_flag);
};
struct npu_if_mbox { struct npu_if_mbox_ops *npu_if_protodrv_mbox_ops; };
struct npu_proto_drv { struct msgid_pool msgid_pool; };
struct npu_frame_counts { atomic_t high_prio_frame_count; atomic_t normal_prio_frame_count; };
struct npu_interface {
	struct mailbox_header *mbox_hdr;
	int (*msgid_get_type)(int);
};

static struct npu_proto_drv npu_proto_drv;
static struct npu_frame_counts g_frame_counts;
static struct npu_frame_counts *protodr = &g_frame_counts;
static struct npu_if_mbox_ops g_mbox_ops;
static struct npu_if_mbox protodrv_mbox = { &g_mbox_ops };
static struct mailbox_header g_mailbox_header;
static struct npu_interface interface;
static struct message g_fw_message;
static struct command g_fw_command;
static int g_fw_message_available;
static int g_fw_get_message_calls;
static int g_fw_get_command_calls;
static int g_fw_note_calls;
static int g_warn_calls;
static int g_debug_calls;
static int g_log_data_calls;
static int g_mock_msgid;
static int g_mock_result_code;
static int g_mock_result_value;
static u32 g_mock_frame_duration;
static int g_mock_frame_result_code;
static int g_fw_manager_return;
static int g_fw_manager_msgid;
static jmp_buf g_bug_escape;
static int g_bug_armed;
static int g_bug_calls;
static int g_failures;

#define likely(value) (value)
#define unlikely(value) (value)
#define BUG_ON(condition) do { if (condition) { \
	g_bug_calls++; \
	if (g_bug_armed) longjmp(g_bug_escape, 1); \
	fprintf(stderr, "unexpected BUG_ON at %s:%d\n", __FILE__, __LINE__); \
	exit(2); \
} } while (0)
#define WARN_ON(condition) ((condition) ? (++g_warn_calls, 1) : 0)
#define npu_dbg(...) do { g_debug_calls++; } while (0)
#define npu_warn(...) do { g_warn_calls++; } while (0)
#define npu_err(...) do { g_warn_calls++; } while (0)
#define npu_info(...) do { } while (0)
#define npu_uinfo(...) do { } while (0)
#define fw_will_note(...) do { g_fw_note_calls++; } while (0)
#define NPU_MBOX_BASE(pointer) (pointer)

static void atomic_set(atomic_t *value, int next) { value->counter = next; }
static int atomic_read(const atomic_t *value) { return value->counter; }
static int atomic_xchg(atomic_t *value, int next)
{
	int old = value->counter;
	value->counter = next;
	return old;
}
static int atomic_cmpxchg(atomic_t *value, int old, int next)
{
	if (value->counter != old)
		return value->counter;
	value->counter = next;
	return old;
}
static void atomic_dec(atomic_t *value) { value->counter--; }

static int mock_nw_get_result(int *msgid, struct npu_nw *result)
{
	*msgid = g_mock_msgid;
	result->result_code = g_mock_result_code;
	result->result_value = g_mock_result_value;
	return 1;
}

static int mock_frame_get_result(int *msgid, struct npu_frame *result,
		enum channel_flag channel)
{
	(void)channel;
	*msgid = g_mock_msgid;
	result->result_code = g_mock_frame_result_code;
	result->duration = g_mock_frame_duration;
	return 1;
}

static int mbx_ipc_peek_msg(void *base, struct mailbox_ctrl *ctrl,
		struct message *message)
{
	(void)base;
	(void)ctrl;
	if (!g_fw_message_available)
		return FALSE;
	*message = g_fw_message;
	return TRUE;
}

static int mbx_ipc_get_msg(void *base, struct mailbox_ctrl *ctrl,
		struct message *message)
{
	(void)base;
	(void)ctrl;
	g_fw_get_message_calls++;
	if (!g_fw_message_available)
		return FALSE;
	*message = g_fw_message;
	g_fw_message_available = 0;
	return TRUE;
}

static int mbx_ipc_get_cmd(void *base, struct mailbox_ctrl *ctrl,
		struct message *message, struct command *command)
{
	(void)base;
	(void)ctrl;
	(void)message;
	g_fw_get_command_calls++;
	*command = g_fw_command;
	return 0;
}

static void fw_rprt_manager(void) { }
static void npu_log_protodrv_set_data(void *object, int type, bool posted)
{
	(void)object;
	(void)type;
	(void)posted;
	g_log_data_calls++;
}

/* ACTUAL_MSGID_FUNCTIONS */
/* ACTUAL_GET_MSGID_TYPE */
/* ACTUAL_NW_RESULT_MANAGER */
/* ACTUAL_FRAME_RESULT_MANAGER */
/* ACTUAL_NW_MBOX_GET */
/* ACTUAL_FRAME_MBOX_GET */

#define CHECK(condition, message) do { \
	if (!(condition)) { \
		fprintf(stderr, "FAIL: %s\n", message); \
		g_failures++; \
	} \
} while (0)

struct guarded_pool {
	struct msgid_pool_entry before;
	struct msgid_pool pool;
};

_Static_assert(offsetof(struct guarded_pool, pool) ==
		sizeof(struct msgid_pool_entry), "negative-ID guard must adjoin pool");

static void reset_mailbox(int msgid)
{
	memset(&g_mailbox_header, 0, sizeof(g_mailbox_header));
	interface.mbox_hdr = &g_mailbox_header;
	interface.msgid_get_type = get_msgid_type;
	memset(&g_fw_message, 0, sizeof(g_fw_message));
	memset(&g_fw_command, 0, sizeof(g_fw_command));
	g_fw_message.mid = msgid;
	g_fw_message.command = COMMAND_DONE;
	g_fw_command.c.done.request_specific_value = 77;
	g_fw_message_available = 1;
	g_fw_get_message_calls = 0;
	g_fw_get_command_calls = 0;
}

static void reset_world(void)
{
	msgid_pool_init(&npu_proto_drv.msgid_pool);
	atomic_set(&g_frame_counts.high_prio_frame_count, 0);
	atomic_set(&g_frame_counts.normal_prio_frame_count, 1);
	g_mbox_ops.nw_get_result = mock_nw_get_result;
	g_mbox_ops.frame_get_result = mock_frame_get_result;
	g_mock_msgid = 0;
	g_mock_result_code = 31;
	g_mock_result_value = 47;
	g_mock_frame_duration = 59;
	g_mock_frame_result_code = 61;
	g_fw_note_calls = 0;
	g_warn_calls = 0;
	g_debug_calls = 0;
	g_log_data_calls = 0;
	g_bug_calls = 0;
	reset_mailbox(0);
}

enum invalid_op { INVALID_CLAIM, INVALID_CLAIM_REF, INVALID_GET_TYPE };
static struct msgid_pool *g_invalid_pool;
static int g_invalid_id;
static enum invalid_op g_invalid_op;
static void *g_invalid_ref_result;
static int g_invalid_type_result;

static void call_invalid_operation(void)
{
	switch (g_invalid_op) {
	case INVALID_CLAIM:
		msgid_claim(g_invalid_pool, g_invalid_id);
		break;
	case INVALID_CLAIM_REF:
		g_invalid_ref_result = msgid_claim_get_ref(g_invalid_pool,
				g_invalid_id, PROTO_DRV_REQ_TYPE_NW);
		break;
	case INVALID_GET_TYPE:
		g_invalid_type_result = msgid_get_pt_type(g_invalid_pool,
				g_invalid_id);
		break;
	}
}

static int catch_invalid_operation(enum invalid_op operation,
		struct msgid_pool *pool, int msgid)
{
	int caught;
	g_invalid_pool = pool;
	g_invalid_id = msgid;
	g_invalid_op = operation;
	g_invalid_ref_result = (void *)(uintptr_t)0x1234;
	g_invalid_type_result = INT_MIN;
	g_bug_armed = 1;
	caught = setjmp(g_bug_escape);
	if (caught == 0)
		call_invalid_operation();
	g_bug_armed = 0;
	return caught != 0;
}

static int catch_bad_handle(struct msgid_pool *pool)
{
	int caught;
	g_invalid_pool = pool;
	g_invalid_id = 0;
	g_invalid_op = INVALID_GET_TYPE;
	g_bug_armed = 1;
	caught = setjmp(g_bug_escape);
	if (caught == 0)
		call_invalid_operation();
	g_bug_armed = 0;
	return caught != 0;
}

static int catch_firmware_nw_result(void)
{
	int caught;
	struct npu_nw result = {0};
	g_bug_armed = 1;
	caught = setjmp(g_bug_escape);
	if (caught == 0)
		g_fw_manager_return = nw_rslt_manager(&g_fw_manager_msgid, &result);
	g_bug_armed = 0;
	return caught != 0;
}

static int catch_firmware_frame_result(void)
{
	int caught;
	struct npu_frame result = {0};
	g_bug_armed = 1;
	caught = setjmp(g_bug_escape);
	if (caught == 0)
		g_fw_manager_return = fr_rslt_manager(&g_fw_manager_msgid, &result,
				MEDIUM_CHANNEL);
	g_bug_armed = 0;
	return caught != 0;
}

static void test_bad_ids_fail_closed(void)
{
	static const int invalid_ids[] = { -1, INT_MIN, 64, INT_MAX };
	struct guarded_pool guarded;
	struct msgid_pool_entry canary = { { 0x1357 }, 0x2468,
		(void *)(uintptr_t)0x369a };
	int following_request = 707;
	int following_id;
	unsigned int i;
	int op;
	int bugs = 0;
	int bug_before;
	int notes_before;

	memset(&guarded, 0, sizeof(guarded));
	msgid_pool_init(&guarded.pool);
	guarded.before = canary;
	following_id = msgid_issue_save_ref(&guarded.pool,
			PROTO_DRV_REQ_TYPE_NW, &following_request, NULL);
	CHECK(following_id == 0, "guarded fixture starts with one legitimate owner");
	for (i = 0; i < sizeof(invalid_ids) / sizeof(invalid_ids[0]); ++i) {
		for (op = INVALID_CLAIM; op <= INVALID_GET_TYPE; ++op) {
			notes_before = g_fw_note_calls;
			bug_before = g_bug_calls;
			bugs += catch_invalid_operation((enum invalid_op)op,
					&guarded.pool, invalid_ids[i]);
#ifdef EXPECT_BASELINE_MSGID_BUG
			CHECK(g_bug_calls == bug_before + 1,
					"baseline invalid input takes exactly one BUG_ON path");
			CHECK(g_fw_note_calls - notes_before ==
					(invalid_ids[i] < 0 ? 0 : 1),
				"baseline invalid-ID failure path retains its old FW note behavior");
#else
			CHECK(g_bug_calls == bug_before,
					"firmware IDs do not trigger kernel BUG_ON");
		CHECK(g_fw_note_calls - notes_before ==
					(invalid_ids[i] >= NPU_MAX_MSG_ID_CNT ? 1 : 0),
					"high invalid IDs retain the prior firmware-report diagnostic");
			if ((enum invalid_op)op == INVALID_CLAIM_REF)
				CHECK(g_invalid_ref_result == NULL,
					"invalid claim_ref returns NULL");
			if ((enum invalid_op)op == INVALID_GET_TYPE)
				CHECK(g_invalid_type_result == -1,
					"invalid get_pt_type returns the existing unknown-type sentinel");
#endif
		}
	}
#ifdef EXPECT_BASELINE_MSGID_BUG
	CHECK(bugs == 12, "baseline BUGs on all negative and out-of-range firmware IDs");
	printf("REPRO: pinned validator BUGs for negative and out-of-range IDs\n");
#else
	CHECK(bugs == 0, "all invalid firmware IDs fail closed without BUG_ON");
#endif
	CHECK(guarded.before.occupied.counter == canary.occupied.counter &&
			guarded.before.pt_type == canary.pt_type &&
			guarded.before.ref == canary.ref,
			"negative invalid ID leaves the adjacent guard entry untouched");
	CHECK(guarded.pool.magic == MSGID_POOL_MAGIC,
			"out-of-range invalid ID leaves the pool magic untouched");
	for (i = 0; i < NPU_MAX_MSG_ID_CNT; ++i)
		CHECK(atomic_read(&guarded.pool.pool[i].occupied) == (i == 0),
				"invalid ID does not release or alter a legitimate request slot");
	CHECK(guarded.pool.pool[0].ref == &following_request &&
			msgid_claim_get_ref(&guarded.pool, following_id,
				PROTO_DRV_REQ_TYPE_NW) == &following_request,
			"valid request still issues and claims after invalid-ID inputs");
}

static void test_invalid_handle_remains_internal_bug(void)
{
	struct msgid_pool bad_magic;
	int null_bug = catch_bad_handle(NULL);

	CHECK(null_bug, "NULL pool remains an internal BUG_ON invariant");
	msgid_pool_init(&bad_magic);
	bad_magic.magic ^= 0x1;
	CHECK(catch_bad_handle(&bad_magic),
		"bad pool magic remains an internal BUG_ON invariant");
}

static void test_all_valid_ids_exhaustion_and_duplicate(void)
{
	struct { int id; } refs[NPU_MAX_MSG_ID_CNT];
	int ids[NPU_MAX_MSG_ID_CNT];
	int i;
	int type;
	void *ref;

	reset_world();
	for (i = 0; i < NPU_MAX_MSG_ID_CNT; ++i) {
		refs[i].id = i;
		type = (i & 1) ? PROTO_DRV_REQ_TYPE_NW : PROTO_DRV_REQ_TYPE_FRAME;
		ids[i] = msgid_issue_save_ref(&npu_proto_drv.msgid_pool,
				type, &refs[i], NULL);
		CHECK(ids[i] == i, "valid allocator preserves every ID in the 0..63 range");
		CHECK(msgid_get_pt_type(&npu_proto_drv.msgid_pool, i) == type,
				"valid type lookup remains unchanged at each pool boundary");
	}
	CHECK(msgid_issue(&npu_proto_drv.msgid_pool, NULL) == -1,
		"valid fully occupied pool still reports exhaustion as -1");
	for (i = 0; i < NPU_MAX_MSG_ID_CNT; ++i) {
		type = (i & 1) ? PROTO_DRV_REQ_TYPE_NW : PROTO_DRV_REQ_TYPE_FRAME;
		ref = msgid_claim_get_ref(&npu_proto_drv.msgid_pool, i, type);
		CHECK(ref == &refs[i], "valid expected-type claim returns its original reference");
		CHECK(atomic_read(&npu_proto_drv.msgid_pool.pool[i].occupied) == 0,
				"valid claim releases exactly its matching slot");
		CHECK(msgid_claim_get_ref(&npu_proto_drv.msgid_pool, i, type) == NULL,
				"duplicate claim of an unoccupied valid slot returns NULL");
		CHECK(msgid_get_pt_type(&npu_proto_drv.msgid_pool, i) == -1,
				"unoccupied valid ID retains the -1 type sentinel");
	}
}

static void test_type_mismatch_preserves_owner(void)
{
	struct proto_req_nw request = { .nw = { .msgid = 101,
		.result_code = 102, .result_value = 103 } };
	int id;
	void *wrong;
#ifndef EXPECT_BASELINE_MSGID_BUG
	void *right;
#endif

	reset_world();
	id = msgid_issue_save_ref(&npu_proto_drv.msgid_pool,
			PROTO_DRV_REQ_TYPE_FRAME, &request, NULL);
	CHECK(id == 0, "mismatch fixture has a valid occupied slot");
	wrong = msgid_claim_get_ref(&npu_proto_drv.msgid_pool, id,
			PROTO_DRV_REQ_TYPE_NW);
#ifdef EXPECT_BASELINE_MSGID_BUG
	CHECK(wrong == &request, "baseline returns a reference despite type mismatch");
	CHECK(atomic_read(&npu_proto_drv.msgid_pool.pool[id].occupied) == 0,
			"baseline mismatch releases the legitimate owner slot");
	CHECK(msgid_claim_get_ref(&npu_proto_drv.msgid_pool, id,
			PROTO_DRV_REQ_TYPE_FRAME) == NULL,
			"baseline mismatch makes the legitimate owner unclaimable");
	printf("REPRO: baseline wrong-type claim returns the reference and releases ownership\n");
#else
	CHECK(wrong == NULL, "wrong expected type returns NULL");
	CHECK(atomic_read(&npu_proto_drv.msgid_pool.pool[id].occupied) == 1,
			"wrong expected type leaves legitimate ownership occupied");
	CHECK(npu_proto_drv.msgid_pool.pool[id].ref == &request,
			"wrong expected type preserves the original reference");
	right = msgid_claim_get_ref(&npu_proto_drv.msgid_pool, id,
			PROTO_DRV_REQ_TYPE_FRAME);
	CHECK(right == &request,
			"later matching owner can still claim the preserved reference");
#endif
}

static void test_actual_mailbox_adapters_fail_closed(void)
{
	struct proto_req_nw nw_request = { .nw = { .msgid = 201,
		.result_code = 202, .result_value = 203 } };
	struct proto_req_frame frame_request;
	struct frame_output output;
	struct proto_req_nw *nw_target = NULL;
	struct proto_req_frame *frame_target = NULL;
	int id;
	int ret;

	reset_world();
	memset(&frame_request, 0, sizeof(frame_request));
	memset(&output, 0, sizeof(output));
	frame_request.frame.msgid = 301;
	frame_request.frame.result_code = 302;
	frame_request.frame.output = &output;
	id = msgid_issue_save_ref(&npu_proto_drv.msgid_pool,
			PROTO_DRV_REQ_TYPE_FRAME, &nw_request, NULL);
	g_mock_msgid = id;
	ret = npu_nw_mbox_ops_get(&npu_proto_drv.msgid_pool, &nw_target);
#ifdef EXPECT_BASELINE_MSGID_BUG
	CHECK(ret == 1 && nw_target == &nw_request,
			"baseline actual NW adapter accepts wrong-type reference");
	CHECK(nw_request.nw.msgid == -1 && nw_request.nw.result_code == g_mock_result_code &&
			nw_request.nw.result_value == g_mock_result_value,
			"baseline actual NW adapter mutates the mismatched request");
	printf("REPRO: actual NW result caller mutates a wrong-type mapped request\n");
#else
	CHECK(ret == 0 && nw_target == NULL,
			"actual NW result caller stops when the helper rejects a wrong type");
	CHECK(nw_request.nw.msgid == 201 && nw_request.nw.result_code == 202 &&
			nw_request.nw.result_value == 203,
			"wrong-type NW result does not mutate the request object");
	CHECK(atomic_read(&npu_proto_drv.msgid_pool.pool[id].occupied) == 1,
			"wrong-type NW result leaves legitimate FRAME ownership intact");
#endif

	msgid_pool_init(&npu_proto_drv.msgid_pool);
	id = msgid_issue_save_ref(&npu_proto_drv.msgid_pool,
			PROTO_DRV_REQ_TYPE_NW, &frame_request, NULL);
	g_mock_msgid = id;
	ret = npu_frame_mbox_ops_get(&npu_proto_drv.msgid_pool, &frame_target);
#ifdef EXPECT_BASELINE_MSGID_BUG
	CHECK(ret == 1 && frame_target == &frame_request,
			"baseline actual frame adapter accepts wrong-type reference");
	CHECK(frame_request.frame.msgid == -1 &&
			frame_request.frame.result_code == g_mock_frame_result_code &&
			output.timestamp[5].tv_sec == (int)g_mock_frame_duration,
			"baseline actual frame adapter mutates the mismatched request");
	printf("REPRO: actual frame result caller mutates a wrong-type mapped request\n");
#else
	CHECK(ret == 0 && frame_target == NULL,
			"actual frame result caller stops when the helper rejects a wrong type");
	CHECK(frame_request.frame.msgid == 301 && frame_request.frame.result_code == 302 &&
			output.timestamp[5].tv_sec == 0,
			"wrong-type frame result does not mutate the request object");
	CHECK(atomic_read(&npu_proto_drv.msgid_pool.pool[id].occupied) == 1,
			"wrong-type frame result leaves legitimate NW ownership intact");
#endif
}

static void test_valid_mailbox_adapters_unchanged(void)
{
	struct proto_req_nw nw_request = {0};
	struct proto_req_nw *nw_target = NULL;
	struct proto_req_frame frame_request;
	struct proto_req_frame *frame_target = NULL;
	struct frame_output output;
	int id;

	reset_world();
	id = msgid_issue_save_ref(&npu_proto_drv.msgid_pool,
			PROTO_DRV_REQ_TYPE_NW, &nw_request, NULL);
	g_mock_msgid = id;
	CHECK(npu_nw_mbox_ops_get(&npu_proto_drv.msgid_pool, &nw_target) == 1 &&
			nw_target == &nw_request && nw_request.nw.msgid == -1 &&
			nw_request.nw.result_code == g_mock_result_code &&
			nw_request.nw.result_value == g_mock_result_value,
			"valid NW mailbox adapter still claims and updates its request");
	CHECK(atomic_read(&npu_proto_drv.msgid_pool.pool[id].occupied) == 0,
			"valid NW mailbox result releases its matching slot");

	msgid_pool_init(&npu_proto_drv.msgid_pool);
	memset(&frame_request, 0, sizeof(frame_request));
	memset(&output, 0, sizeof(output));
	frame_request.frame.output = &output;
	id = msgid_issue_save_ref(&npu_proto_drv.msgid_pool,
			PROTO_DRV_REQ_TYPE_FRAME, &frame_request, NULL);
	g_mock_msgid = id;
	CHECK(npu_frame_mbox_ops_get(&npu_proto_drv.msgid_pool, &frame_target) == 1 &&
			frame_target == &frame_request && frame_request.frame.msgid == -1 &&
			frame_request.frame.result_code == g_mock_frame_result_code &&
			output.timestamp[5].tv_sec == (int)g_mock_frame_duration,
			"valid frame mailbox adapter still claims and updates its request");
	CHECK(atomic_read(&npu_proto_drv.msgid_pool.pool[id].occupied) == 0,
			"valid frame mailbox result releases its matching slot");
}

static void test_firmware_result_type_gate_and_valid_delivery(void)
{
	struct npu_nw nw = {0};
	int msgid;
	int ret;
	int i;
	int notes_before;
	int owner_reference = 811;
	int owner_id;
	static const int invalid_ids[] = { -1, INT_MIN, 64, INT_MAX };

	reset_world();
	owner_id = msgid_issue_save_ref(&npu_proto_drv.msgid_pool,
			PROTO_DRV_REQ_TYPE_FRAME, &owner_reference, NULL);
	CHECK(owner_id == 0, "invalid firmware-result tests retain a real slot owner");
	for (i = 0; i < (int)(sizeof(invalid_ids) / sizeof(invalid_ids[0])); ++i) {
		notes_before = g_fw_note_calls;
		reset_mailbox(invalid_ids[i]);
#ifdef EXPECT_BASELINE_MSGID_BUG
		CHECK(catch_firmware_nw_result(),
				"baseline firmware NW path BUGs on an invalid message ID");
		printf("REPRO: firmware NW result path reaches BUG_ON before dequeue\n");
#else
		CHECK(!catch_firmware_nw_result(),
				"firmware NW invalid ID does not BUG");
		ret = g_fw_manager_return;
		CHECK(ret == FALSE && g_fw_get_message_calls == 0 &&
				g_fw_get_command_calls == 0 && g_fw_message_available,
				"firmware NW invalid ID is rejected before mailbox dequeue");
#endif
		CHECK(g_fw_note_calls - notes_before ==
				(invalid_ids[i] >= NPU_MAX_MSG_ID_CNT ? 1 : 0),
				"firmware-result rejection preserves the existing high-ID diagnostic");
		reset_mailbox(invalid_ids[i]);
		notes_before = g_fw_note_calls;
#ifdef EXPECT_BASELINE_MSGID_BUG
		CHECK(catch_firmware_frame_result(),
				"baseline firmware frame path BUGs on an invalid message ID");
		printf("REPRO: firmware frame result path reaches BUG_ON before dequeue\n");
#else
		CHECK(!catch_firmware_frame_result(),
				"firmware frame invalid ID does not BUG");
		ret = g_fw_manager_return;
		CHECK(ret == FALSE && g_fw_get_message_calls == 0 &&
				g_fw_get_command_calls == 0 && g_fw_message_available,
				"firmware frame invalid ID is rejected before mailbox dequeue");
#endif
		CHECK(g_fw_note_calls - notes_before ==
				(invalid_ids[i] >= NPU_MAX_MSG_ID_CNT ? 1 : 0),
				"frame-result rejection preserves the existing high-ID diagnostic");
		CHECK(atomic_read(&npu_proto_drv.msgid_pool.pool[owner_id].occupied) == 1 &&
				npu_proto_drv.msgid_pool.pool[owner_id].ref == &owner_reference,
				"invalid firmware result ID does not reclaim the valid mapped owner");
	}

#ifndef EXPECT_BASELINE_MSGID_BUG
	reset_world();
	CHECK(msgid_issue_save_ref(&npu_proto_drv.msgid_pool,
			PROTO_DRV_REQ_TYPE_NW, &nw, NULL) == 0,
			"valid NW firmware result has a mapped owner");
	reset_mailbox(0);
	ret = nw_rslt_manager(&msgid, &nw);
	CHECK(ret == TRUE && msgid == 0 && g_fw_get_message_calls == 1 &&
			g_fw_get_command_calls == 1 && nw.result_value == 77,
			"valid firmware NW result follows the unchanged type/dequeue path");

	{
		struct proto_req_frame owner;
		struct proto_req_frame *owner_target = NULL;
		struct frame_output output;
		struct npu_frame result = {0};

		msgid_pool_init(&npu_proto_drv.msgid_pool);
		memset(&owner, 0, sizeof(owner));
		memset(&output, 0, sizeof(output));
		owner.frame.output = &output;
		CHECK(msgid_issue_save_ref(&npu_proto_drv.msgid_pool,
				PROTO_DRV_REQ_TYPE_FRAME, &owner, NULL) == 0,
				"valid frame firmware result has a mapped owner");
		reset_mailbox(0);
		CHECK(nw_rslt_manager(&msgid, &nw) == FALSE &&
				g_fw_get_message_calls == 0 && g_fw_message_available &&
				atomic_read(&npu_proto_drv.msgid_pool.pool[0].occupied) == 1,
				"NW result gate leaves a valid FRAME owner queued and occupied");
		reset_mailbox(0);
		CHECK(fr_rslt_manager(&msgid, &result, MEDIUM_CHANNEL) == TRUE &&
				msgid == 0 && g_fw_get_message_calls == 1 &&
				g_fw_get_command_calls == 1,
				"matching frame result gate consumes the valid frame response");
		g_mock_msgid = msgid;
		CHECK(npu_frame_mbox_ops_get(&npu_proto_drv.msgid_pool,
				&owner_target) == 1 && owner_target == &owner &&
				atomic_read(&npu_proto_drv.msgid_pool.pool[0].occupied) == 0,
				"valid frame owner remains claimable after the NW type gate rejects it");
	}
#else
	(void)ret;
	(void)msgid;
	(void)nw;
#endif
}

int main(void)
{
	reset_world();
	test_bad_ids_fail_closed();
	test_invalid_handle_remains_internal_bug();
	test_all_valid_ids_exhaustion_and_duplicate();
	test_type_mismatch_preserves_owner();
	test_actual_mailbox_adapters_fail_closed();
	test_valid_mailbox_adapters_unchanged();
	test_firmware_result_type_gate_and_valid_delivery();
	if (g_failures) {
		fprintf(stderr, "%d host assertions failed\n", g_failures);
		return 1;
	}
	puts("PASS: extracted pinned msgid allocator, validator, mailbox adapters, and firmware result gates");
	return 0;
}
